# Coding Tutorial 1: Neural Networks and PyTorch

```
Course: CSCI 5922 Spring 2025, University of Colorado Boulder
TA: Everley Tseng
Email: Yu-Yun.Tseng@colorado.edu
* AI assistant is used in making this tutorial
```


[Lecture Video](https://o365coloradoedu-my.sharepoint.com/:v:/g/personal/yuts1923_colorado_edu/EXWgjy1sF91Kp3t2K4pSIoIBRyLU_BKSbFrOgYcMbkvqWA?e=O5YltB&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

Welcome to our first coding tutorial! I’m your TA, Everley, and I’ll be leading the coding tutorials this semester. These are designed to help you build a solid foundation in deep learning, by complementing what you learn in class with hands-on deep learning implementations.

We’ll focus on topics that are essential for your lab assignments, but some tutorials will also include optional sections that explore advanced concepts to expand your knowledge. We’ll share external links and resources in these tutorials to help you dive deeper into the material. Additionally, we will provide videos where I walk you through the script for each tutorial.

I welcome any real-time feedback on how we can improve these tutorials to support your learning experience. I’m looking forward to a semester of learning and coding with all of you!


## Overview

Sections:
- Introduction to Google Colaboratory
- Introduction to PyTorch
- Coding in PyTorch:
  1. Introduction to tensors
  2. Common ways to use tensors
  3. PyTorch built-ins

Objectives:
- Learn how to use Colab to run Python scripts
- Learn how to use a `tensor` in PyTorch
- Learn how to utilize library documentation

## Introduction to Google Colaboratory

**Google Colab** is a cloud-based platform that allows you to run Python notebooks without needing to install anything on your computer. We will use Colab for most coding tutorials this semester.

To start Google Colab, you will need to sign in to a Google account. Go to this [link](https://colab.research.google.com/) to open your first script. By default, you will have read-only access to the tutorials, meaning you cannot directly run the code. To run the code, you must **copy the tutorial** to your own Google Drive.

### Python Notebook

**Colab** files are in Python notebook format. **Python notebooks** are interactive documents that combine code, text, and visualizations in a single interface. In a Python Notebook, you can create text cells and code cells using the toolbar at the top left of the page. **Text cells** (or markdown cells) display descriptive content, like the one you are currently reading. **Code cells** contain Python code that you can execute by clicking on the ▶ button located on the far left of the cell. Alternatively, you can run a cell by pressing **Shift + Enter** on your keyboard. You can view a high-level summary of what is covered in each tutorial by clicking the `Table of contents` symbol in the left sidebar. To collapse the cells in a section, click on the &or; symbol on the left of the section title.

### Computing Resources

By default, Colab provides access to a **CPU** as the computing resource. To connect to a GPU, navigate to **Runtime > Change runtime type**, and select an available GPU. Since Colab's computing resources are provided for free, GPU usage is limited, and the session will terminate once you reach the usage limit. If needed, you can connect a Colab notebook to paid GPU resources on Google Cloud. In the first few tutorials, we will only use CPUs (default) for training. GPU usages will be covered in future tutorials.


### External Resources
- Google Colaboratory [FAQ](https://research.google.com/colaboratory/faq.html)
- What is a markdown cell and how do I code it? [GeeksforGeeks: Markdown cell in Jupyter Notebook](https://www.geeksforgeeks.org/markdown-cell-in-jupyter-notebook/)
- What is a CPU and what is a GPU? [Google Cloud: Introduction to Cloud TPU](https://cloud.google.com/tpu/docs/intro-to-tpu)


## Introduction to PyTorch

In this course, we will primarily use the Python package **PyTorch** to support deep learning coding. PyTorch is a deep learning framework that has gained significant popularity in both industry and academia. You will be required to use PyTorch for lab assignments, as it provides a strong foundation for understanding and implementing deep learning models.

While PyTorch will be the only required framework in lab assignments, we will also provide optional tutorials to introduce other commonly used frameworks. Understanding multiple frameworks will give you insight into the different tools available and help you make informed decisions about which framework to use in the future.

### What is a Tensor?

A **tensor** is a fundamental building block in deep learning and represents a **multi-dimensional array** of numbers. You can think of it as an advanced version of arrays or matrices from mathematics, capable of holding data in higher dimensions. Here are some examples of tensors:
- A scalar: A single number (0D tensor). Example: 5
- A vector: A list of numbers (1D tensor). Example: `[1, 2, 3]`
- A matrix: A grid of numbers (2D tensor). Example: `[[1, 2], [3, 4]]`

### Why Are Tensors Used for Deep Learning?

Deep learning involves lots of multi-dimensional arrays, which can be represented by tensors. Here are some examples of how tensors are used:
- **Data Representation**: Tensors are used to represent inputs (e.g., images, text, audio) and outputs for deep learning models.
Example: An image can be represented as a 3D tensor with dimensions [channels, height, width].
- **Model Parameters**: Neural network weights and biases are stored as tensors.
- **Efficient Computations**: Tensors are optimized for operations on GPUs, making deep learning computations faster.
- **Intermediate Calculations**: During forward and backward passes, tensors store intermediate results and gradients.

The `torch` library simplifies working with these tensors.


### External Resources

- PyTorch documentation: [PyTorch index](https://pytorch.org/docs/stable/index.html)
- Tensors in PyTorch: [Tensor](https://pytorch.org/docs/stable/tensors.html)
- To use PyTorch locally (not on Colab), install the package following the instructions on [this page](https://pytorch.org/).

## Coding PyTorch

Import the library:

In [ ]:
import torch

### Introduction to Tensor

- The tensor class in PyTorch: [`torch.tensor`](https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor)



#### Create a Tensor
Let practice creating tensors in different shapes:

In [ ]:
# Scalar (0D tensor)
scalar = torch.tensor(5)
print('Scalar: {}'.format(scalar))

# Vector (1D tensor)
vector = torch.tensor([1, 2, 3])
print('Vector:', vector)

# Matrix (2D tensor)
matrix = torch.tensor([[1, 2], [3, 4]])
print('Matrix:', matrix)

# Higher-dimensional tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print('3D tensor:', tensor_3d)
print('3D Tensor shape:', tensor_3d.shape)

Scalar: 5
Vector: tensor([1, 2, 3])
Matrix: tensor([[1, 2],
        [3, 4]])
3D tensor: tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
3D Tensor shape: torch.Size([3, 2, 2])


#### Ways to Initialize a Tensor

1. Initialize a tensor with assigned elements (as demonstrated in the above cell)
2. Initialize all values of assigned dimension to 1, `torch.ones` ([documentation](https://pytorch.org/docs/stable/generated/torch.ones.html))
3. Initialize all values of assigned dimension to 0, `torch.zeros` ([documentation](https://pytorch.org/docs/stable/generated/torch.zeros.html))
4. Initialize a 1D tensor within an assigned range, `torch.arange()` ([documentation](https://pytorch.org/docs/stable/generated/torch.arange.html))

In [ ]:
# assigning elements
x = torch.tensor([[1,2], [3,4]])
print(x)

# all 1s
x = torch.ones((4, 3))
print(x)

# all 0s
x = torch.zeros((2, 2))
print(x)

# 1D tensor from 0 to 9
x = torch.arange(10)
print(x)


tensor([[1, 2],
        [3, 4]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


5. Initialize a tensor with random values
  - `torch.rand` ([documentation](https://pytorch.org/docs/main/generated/torch.rand.html)): Generates a tensor with random numbers uniformly distributed in the range `[0, 1)`.
  - `torch.randn` ([documentation](https://pytorch.org/docs/main/generated/torch.randn.html)): Generates a tensor with random numbers from a standard normal distribution `(mean = 0, std = 1).
  - `torch.randint` ([documentation](https://pytorch.org/docs/stable/generated/torch.randint.html)): Generates a tensor with random integers in a specified range.
  - `torch.rand_like` ([documentation](https://pytorch.org/docs/stable/generated/torch.rand_like.html)): Creates a tensor with random numbers, matching the shape and device of an existing tensor.
  - `torch.randn_like` ([documentation](https://pytorch.org/docs/stable/generated/torch.randn_like.html)): Generates a tensor with random numbers from a normal distribution, matching the shape of an existing tensor.
  - `torch.randint_like` ([documentation](https://pytorch.org/docs/stable/generated/torch.randint_like.html)): Generates random integers in a specified range, matching the shape of an existing tensor.

In [ ]:
tensor_random_A = torch.rand(2, 3, 4) # pass in the shape
tensor_random_B = torch.randn_like(tensor_random_A) # pass in the tensor of which shape is to be matched

print(tensor_random_A)
print('A shape: {}, B shape: {}'.format(tensor_random_A.shape, tensor_random_B.shape))

tensor([[[0.2484, 0.0518, 0.8300, 0.4637],
         [0.2312, 0.1527, 0.0196, 0.1769],
         [0.4258, 0.8843, 0.6201, 0.7928]],

        [[0.4456, 0.6263, 0.8956, 0.3035],
         [0.7094, 0.0537, 0.4713, 0.2053],
         [0.8963, 0.7265, 0.8068, 0.7315]]])
A shape: torch.Size([2, 3, 4]), B shape: torch.Size([2, 3, 4])


#### Tensor Basic Operations

- Arithmetic operations: element-wise $+$, $-$, $\times$, and $\div$

In [ ]:
a = torch.tensor([9, 2, 3])
b = torch.tensor([4, 5, 6])

print('Addition:', a + b)
print('Subtraction:', a - b)
print('Element-wise Multiplication:', a * b)
print('Division:', a / b)

Addition: tensor([13,  7,  9])
Subtraction: tensor([ 5, -3, -3])
Element-wise Multiplication: tensor([36, 10, 18])
Division: tensor([2.2500, 0.4000, 0.5000])


- Matrix multiplication: [`torch.matmul()`](https://pytorch.org/docs/main/generated/torch.matmul.html) or `@`

In [ ]:
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

result = torch.matmul(matrix1, matrix2)
print('Matrix Multiplication:\n', result)

result = matrix1 @ matrix2
print('Matrix Multiplication:\n', result)

Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])
Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])


- Reshaping a Tensor: [`torch.tensor.view()`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) or [`torch.reshape()`](https://pytorch.org/docs/stable/generated/torch.reshape.html)

In [ ]:
tensor = torch.arange(12)
print('Initialize a 1D tensor:',tensor.shape, '\n', tensor)

# Reshape to a 3x4 matrix
reshaped = tensor.view(3, 4)
print('Reshaped 3x4 tensor:',reshaped.shape, '\n', reshaped)

# Flatten back to 1D
flattened = reshaped.view(-1)  # -1 automatically infers the size
print("Flattened 1D tensor:", flattened.shape, '\n', flattened)

# Reshape to a 4x? matrix
reshaped = tensor.view(4, -1)
print('Reshaped 4x? tensor:', reshaped.shape, '\n', reshaped) # 4x3, where 3 is automatically calculated

# Reshape to ?x2 matrix
reshaped = torch.reshape(reshaped, (-1, 2))
print('Reshaped ?x2 tensor:', reshaped.shape, '\n', reshaped) # 6x2

Initialize a 1D tensor: torch.Size([12]) 
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped 3x4 tensor: torch.Size([3, 4]) 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Flattened 1D tensor: torch.Size([12]) 
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped 4x? tensor: torch.Size([4, 3]) 
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
Reshaped ?x2 tensor: torch.Size([6, 2]) 
 tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


- Aggregations: [`torch.sum`](https://pytorch.org/docs/stable/generated/torch.sum.html), [`torch.mean`](https://pytorch.org/docs/stable/generated/torch.mean.html), [`torch.max`](https://pytorch.org/docs/main/generated/torch.max.html), etc.

In [ ]:
tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print("Sum:", tensor.sum())
print("Mean:", tensor.mean(dim=0))
print("Max value: ", tensor.max(dim=1).values, ', index:', tensor.max(dim=1).indices)

Sum: tensor(21.)
Mean: tensor([2.5000, 3.5000, 4.5000])
Max value:  tensor([3., 6.]) , index: tensor([2, 2])


### Common Ways to Use Tensors

#### Model Layer

One common use of tensors is for building layers in a model. Let's practice using a **linear layer** with tensors and the operators we learned.

Function: $y = xW + bias$

In [ ]:
# Input data
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# Weights and biases
weights = torch.tensor([[0.5, 1.0], [1.5, 2.0]])
bias = torch.tensor([1.0, 0.5])

# Linear transformation: y = xW + b
y = torch.matmul(x, weights) + bias
print('Output:\n', y)

Output:
 tensor([[ 4.5000,  5.5000],
        [ 8.5000, 11.5000]])


#### Dataset




Let's design a **binary classification dataset**
- `x`: Every data has 3 features $(X_1, X_2, X_3)$. Generate 10 samples.


In [ ]:
num_samples = 10
num_features = 3

x_train = torch.rand(num_samples, num_features) # Generate random x samples

# See the first sample
print('x shape: {}, first sample: {}'.format(x_train.shape, x_train[:1]))

x shape: torch.Size([10, 3]), first sample: tensor([[0.8562, 0.2390, 0.4661]])


### PyTorch Built-ins

While it is essential to learn how to operate the tensors, we should note that the `torch` library has many built-in modules for us to utilize. Calling the built-in modules saves us coding time, but it is important to read the documentation carefully before using them. Below, we will first use some built-in layers to build a simple MLP model and then load a built-in dataset.

In [ ]:
import torch.nn as nn

 #### Layers

- [`nn.Linear`](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html): a linear layer (with random initialization)

Note that this `nn.Linear` resembles the operation we implemented earlier. However, the built-in function initializes the parameters (e.g., weights and biases) randomly and their default mode is `requires_grad=True`.

In [ ]:
x = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]])

# Define a linear layer
linear = nn.Linear(in_features=3, out_features=2)

# Forward pass x into the layer
output = linear(x)
print('Output:\n', output)

# Display the weights and biases randomly initialized
print('Initial weights:\n', linear.weight)
print('Initial bias:\n', linear.bias)

Output:
 tensor([[ 3.0126, -0.2027],
        [ 6.7889, -0.9472]], grad_fn=<AddmmBackward0>)
Initial weights:
 Parameter containing:
tensor([[ 0.4161,  0.3290,  0.5137],
        [-0.1187,  0.0608, -0.1902]], requires_grad=True)
Initial bias:
 Parameter containing:
tensor([0.3975, 0.3651], requires_grad=True)


#### Model Structure

To define the structure of your neural network, [`nn.Module`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module) is the base class for all neural network modules.

Let's try to build a Multi-Layer Perceptron (MLP) model.


In [ ]:
class MultiLayerPerceptron(nn.Module):
  def __init__(self, input_size, output_size):
    super(MultiLayerPerceptron, self).__init__()
    self.input_size = input_size
    self.output_size = output_size

    # Define all layers in the model
    self.linear1 = nn.Linear(self.input_size, 10)
    self.activation1 = nn.ReLU()
    self.linear2 = nn.Linear(10, self.output_size)
    self.activation2 = nn.Sigmoid()

  def forward(self, x):
    # Build the feed forward structure
    linear1 = self.linear1(x)
    act1 = self.activation1(linear1)
    linear2 = self.linear2(act1)
    output = self.activation2(linear2)
    return output

Now, let's pass data into the model:

In [ ]:
model = MultiLayerPerceptron(input_size=num_features, output_size=1)

# pass the first data in x_train to the model
output_values = model(x_train[:1])
print('Model output of passing one data:\n', output_values)

# pass the all data in x_train to the model
output_values = model(x_train)
print('Model output of passing 10 samples (in x_train):\n', output_values)

Model output of passing one data:
 tensor([[0.4530]], grad_fn=<SigmoidBackward0>)
Model output of passing 10 samples (in x_train):
 tensor([[0.4530],
        [0.4523],
        [0.4408],
        [0.4493],
        [0.4364],
        [0.4365],
        [0.4406],
        [0.4474],
        [0.4377],
        [0.4443]], grad_fn=<SigmoidBackward0>)


#### Loading a Dataset


Let's now review how to load one of PyTorch's built-in datasets, [MNIST](https://pytorch.org/vision/0.20/generated/torchvision.datasets.MNIST.html):
1. Load the dataset
2. Transform the dataset into tensor format
3. Read one sample and print the tensor shape


In [ ]:
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor()])

mnist_dataset = datasets.MNIST(root='./data', transform=transform, download=True)
print('Total data size:', len(mnist_dataset))

# Print the first sample
sample_image, sample_label = mnist_dataset[0]
print('Sample image shape:', sample_image.shape)
print('Sample label:', sample_label)

Total data size: 60000
Sample image shape: torch.Size([1, 28, 28])
Sample label: 5


## Review

In the next tutorial, we will teach you how to build and train a model using all the built-in modules we talked about in this tutorial. Before then, we encourage you to practice tensor operations **without** the built-in modules.

You can try the following practices:

1. Create a 3x3 tensor filled with random values and compute the row-wise mean.
2. Perform element-wise multiplication on two tensors of size 2x2.
3. Create a 2D tensor, reshape it to a 3D tensor, and then flatten it back.


For any questions and discussions regarding this tutorial, attend [TA office hours](https://docs.google.com/spreadsheets/d/1fzfTJpEF7RaUYRA_NGa3DkiazdQXVj7QNBbp6DrEZ3I/edit?usp=sharing) or create a post on [Piazza](https://piazza.com/colorado/spring2025/csci5922/home) :) See you in the next tutorial!

\- Everley